### ISSUE TITLE
Naming issue

### ISSUE THREAD

**Issue by jezdez** [JohnnyPeng18/PyConf#1]
Hi there!

I was made aware of your paper ["Less is More? An Empirical Study on Configuration Issues in Python PyPI Ecosystem"](https://arxiv.org/pdf/2310.12598.pdf) and would strongly suggest for you to reach out to the [Python Software Foundation trademarks working](https://www.python.org/psf/workgroups/#trademarks-work-group) group to discuss the use of "PyCon" as proposed in the paper.

For context: "PyCon" has been used for years for [Python conferences](https://pycon.org), and the overlap with your paper might not be useful for discoverability and reducing confusion at least.

Thank you!

**Comment by JohnnyPeng18** [comment]
Thanks for your suggestion. We have renamed our tool to PyConf.
